env:
  browser: true
  commonjs: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules: {
  "spellcheck/spell-checker": [1,
       {
           "comments": true,
           "strings": true,
           "identifiers": true,
           "lang": "en_US",
           "skipWords": [
               "netlify",
               "toml",
               "sitrep",
               "iframe",
               "ifrm"
           ],
           "minLength": 3
        }
    ]
}
plugins:
  - spellcheck
