# Netlify doesn't support context-dependent plugins yet, so for now
# we manually switch plugin configs during dev deploys

[[plugins]]
package = "@netlify/plugin-local-install-core"

# Development
# [context.branch-deploy]
# [[plugins]]
# package = "../"
#   [plugins.inputs]  
#     "allow_prod" = ""
#     "verbose" = "true"

# Production
[context.production]
[[plugins]]
package = "../"
  [plugins.inputs]  
    "allow_prod" = "true"
    "verbose" = ""